# Generated by Django 3.1.2 on 2020-11-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201129_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='unique_key',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
