# Generated by Django 3.1.2 on 2020-11-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201129_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unique_key',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
