# Generated by Django 3.1.2 on 2020-11-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderitem_unique_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unique_key',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
