# Generated by Django 3.1.2 on 2020-11-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201129_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='thing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.thing'),
        ),
    ]
